name: Build and Deploy

on:
  push:
    branch:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install and Build
        run: |
          yarn
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@master
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist